// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfle1GO6m6Jq_rnkywhwVYsXxjrOeQBoA',
    appId: '1:1079121665235:web:3de350779e3db8e9ef4826',
    messagingSenderId: '1079121665235',
    projectId: 'umeed-e-hayat',
    authDomain: 'umeed-e-hayat.firebaseapp.com',
    storageBucket: 'umeed-e-hayat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrHXRDDKGUQwWPZyfdvr9w3l8YHlbsUpU',
    appId: '1:1079121665235:android:0c3f51b3ba09b29aef4826',
    messagingSenderId: '1079121665235',
    projectId: 'umeed-e-hayat',
    storageBucket: 'umeed-e-hayat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0liwut-29DhjKbvmpb6XX35ri0J3097Q',
    appId: '1:1079121665235:ios:f9977d11f3482a17ef4826',
    messagingSenderId: '1079121665235',
    projectId: 'umeed-e-hayat',
    storageBucket: 'umeed-e-hayat.appspot.com',
    iosClientId: '1079121665235-sqdnis4qvkdqh4trt4j43a9dvjav2poi.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );
}
